title: <p align="center"> Akshath K R </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/akshath-kr-541049a6/">LinkedIn</a> |
  <a href="https://github.com/Akshath-KR">GitHub</a>
  
  <br>   
  Description here
  <br>
  </p>
