title: <p align="center"> Akshath K R </p>
logo: assets/img/GIT_IMG_20220501_160509-01.jpeg

description:
  <p align="center">
  <a href="docs/Akshath K R_Resume_Data Science.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/akshath-kr-541049a6/">LinkedIn</a> |
  <a href="https://github.com/Akshath-KR">GitHub</a>
  
  <br>   
  Analytical, ambitious and resourceful individual seeking for a challenging position in the field of Data Science and Management, to employ my expertise in delivering meaningful and insightful content that attains desired business outcomes and to utilize my communication and interpersonal skills to achieve better relationships with stakeholders and aid organizations to achieve their goals through the effective utilization of data science methodologies.
  <br>
  </p>
